import Head from 'next/head';
import styles from './Signup.module.css';
import { useRouter } from 'next/router';

export default function Signup() {
	const router = useRouter();
	return (
		<div className={styles.container}>
			<Head>
				<title>Buy 1 Take 1</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.body}>
				<div className={styles.landing_page}>
					<form
						className={styles.form_signin}
						onSubmit={(e) => {
							e.preventDefault;
						}}>
						<h1 className={styles.heading_text}>
							Create an Account
						</h1>
						<h5 className={styles.label_text}>Email</h5>
						<div className={styles.input_container}>
							<input type='text' className={styles.input_form} />
						</div>
						<h5 className={styles.label_text}>Username</h5>
						<div className={styles.input_container}>
							<input type='text' className={styles.input_form} />
						</div>
						<h5 className={styles.label_text}>Password</h5>
						<div className={styles.input_container}>
							<input
								type='password'
								className={styles.input_form}
							/>
						</div>
						<h5 className={styles.label_text}>Confirm Password</h5>
						<div className={styles.input_container}>
							<input
								type='password'
								className={styles.input_form}
							/>
						</div>

						<button type='submit' className={styles.button_primary}>
							Sign Up
						</button>
						<button
							type='button'
							className={styles.button_secondary}
							onClick={(e) => {
								e.preventDefault;
								router.push('/');
							}}>
							Go Back Home
						</button>
						<div className={styles.button_tertiary_container}>
							Already have an account?
							<button
								className={styles.button_tertiary}
								onClick={(e) => {
									e.preventDefault;
									router.push('/signin');
								}}>
								Signin
							</button>
						</div>
					</form>
				</div>
			</main>
		</div>
	);
}
